version: '3.4'

services:
  longestincreasingsubsequence.test:
    container_name: longestincreasingsubsequence.test
    image: mcr.microsoft.com/dotnet/sdk:2.1
    build:
      context: .
      dockerfile: LongestIncreasingSubsequence.Test/Dockerfile
    volumes:
      - .:/src
    working_dir: /src
    command:
      [
        "dotnet",
        "test",
        "LongestIncreasingSubsequence.Test/LongestIncreasingSubsequence.Test.csproj"
      ]